# Generated by Django 4.0.5 on 2024-04-29 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twelioapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foundation',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
