# Generated by Django 4.0.5 on 2024-04-29 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twelioapi', '0002_foundation_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailrecord',
            name='nonprofit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='twelioapi.nonprofit'),
        ),
        migrations.AlterField(
            model_name='emailrecord',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='foundation',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='nonprofit',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
