# Generated by Django 4.0.5 on 2024-04-29 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twelioapi', '0003_emailrecord_nonprofit_alter_emailrecord_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailrecord',
            name='recipient_email',
        ),
    ]
